---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - clusters:
        values:
          addonChart: external-secrets
          addonChartVersion: 0.9.19
          addonChartRepository: https://charts.external-secrets.io
        selector:
          matchExpressions:
            - key: enable_external_secrets
              operator: In
              values: ["true"]
  template:
    metadata:
      name: addon-{{name}}-{{values.addonChart}}
    spec:
      project: default
      sources:
        - repoURL: "{{metadata.annotations.addons_repo_url}}"
          targetRevision: "{{metadata.annotations.addons_repo_revision}}"
          ref: values
        - chart: "{{values.addonChart}}"
          repoURL: "{{values.addonChartRepository}}"
          targetRevision: "{{values.addonChartVersion}}"
          helm:
            releaseName: "{{values.addonChart}}"
            ignoreMissingValueFiles: true
            #valueFiles:
            #  - $values/{{metadata.annotations.addons_repo_basepath}}environments/default/addons/{{values.addonChart}}/values.yaml
            #  - $values/{{metadata.annotations.addons_repo_basepath}}environments/{{metadata.labels.environment}}/addons/{{values.addonChart}}/values.yaml
            #  - $values/{{metadata.annotations.addons_repo_basepath}}clusters/{{name}}/addons/{{values.addonChart}}/values.yaml
            values: |
              serviceAccount:
                name: {{name}} 
                annotations:
                eks.amazonaws.com/role-arn: arn:aws:iam::{{metadata.annotations.account_id}}:role/{{name}}
      destination:
        namespace: "{{name}}"
        name: "{{name}}"
      syncPolicy:
        automated: {}
        syncOptions: [CreateNamespace=true, ServerSideApply=true]
